{
 "title": "AWS WAF Global Dashboard",
 "tags": [
  "AWS",
  "WAFv2",
  "Amazon",
  "CloudWatch",
  "Logs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "cloudwatch" },
   { "name": "region", "label": "Region" },
   {
    "name": "env",
    "label": "Environment",
    "query": {}
   },
   {
    "name": "wafLogs",
    "label": "WAF Log Group",
    "query": {}
   },
   {
    "name": "webAcl",
    "label": "Web ACL",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Top 100 IPs",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expression": "fields httpRequest.clientIp\n| stats count(*) as requestCount by httpRequest.clientIp\n| sort requestCount desc\n| limit 100",
     "logGroupNames": [ "$wafLogs" ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "httpRequest.clientIp" ]
    }
   ]
  },
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields httpRequest\n| stats count() as Method ",
     "logGroupNames": [ "$wafLogs" ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "Locations",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expression": "fields httpRequest.country\n| stats count(*) as requestCount by httpRequest.country\n| sort requestCount desc\n| limit 100",
     "logGroupNames": [ "$wafLogs" ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "httpRequest.country" ]
    }
   ]
  },
  {
   "title": "Request Methods",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields httpRequest.httpMethod\n| stats count(*) as Method by httpRequest.httpMethod\n| limit 100",
     "logGroupNames": [ "$wafLogs" ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "httpRequest.httpMethod" ]
    }
   ]
  },
  {
   "title": "Top User Agent",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| parse @message '{\"name\":\"User-Agent\",\"value\":\"*\"}' as userAgent\n| stats count(*) as requestCount by userAgent\n| sort requestCount desc\n| limit 100",
     "logGroupNames": [ "$wafLogs" ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "userAgent" ]
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "alias": "Allowed Requests",
     "dimensions": { "Region": "$region", "Rule": "ALL", "WebACL": "$webAcl" },
     "metricName": "AllowedRequests",
     "namespace": "AWS/WAFV2",
     "queryMode": "Metrics",
     "region": "default",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "statistic": "Sum"
    },
    {
     "alias": "Blocked Requests",
     "dimensions": { "Region": "$region", "Rule": "ALL", "WebACL": "$webAcl" },
     "metricName": "BlockedRequests",
     "namespace": "AWS/WAFV2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "alias": "Counted Requests",
     "dimensions": { "Region": "$region", "Rule": "ALL", "WebACL": "$webAcl" },
     "metricName": "CountedRequests",
     "namespace": "AWS/WAFV2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "alias": "Passed Requests",
     "dimensions": { "Region": "$region", "Rule": "*", "WebACL": "$webAcl" },
     "metricName": "PassedRequests",
     "namespace": "AWS/WAFV2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}